<?php 

function fixEncoding ( $string, $encodeFrom = "windows-1252", $encodeTo = "UTF-8"){
    return mb_convert_encoding ( $string, $encodeFrom, $encodeTo );
}

$string = '<h1><a href="issues/hackwork/contributors-3/dan-sociu/#27">Dan Sociu</a></h1>
<p><br>Se hotÄƒrÃ®se deodatÄƒ sÄƒ devinÄƒ vegetarian. Joan era vegetarianÄƒ ÅŸi, de cÃ®te ori mÃ®ncau Ã®mpreunÄƒ, se simÅ£ea uÅŸor ÅŸi special. VÄƒzuse un film pe care i-l recomandase RareÅŸ despre industria abatoarelor, puÅ£in cam didactic, dar, Ã®ntr-un fel, nu destul de didactic. Bunicul sÄƒu, mÄƒcelarul, Ã®l luase de multe ori cu el Ia muncÄƒ, le vÄƒzuse pe toate. Dar, dacÄƒ atunci imaginea viÅ£eilor Ã®nchiÅŸi cÃ®teva luni Ã®n locuri sufocante, fÄƒrÄƒ aer ÅŸi luminÄƒ ÅŸi hrÄƒniÅ£i cu mÃ®ncare proastÄƒ, lipsitÄƒ de fier, pentru ca apoi sÄƒ fie omorÃ®Å£i, nu erau pentru DuÅ£u deloc tulburÄƒtoare, fÄƒceauÂ  parte din aceeaÅŸi filozofie, viaÅ£a e grea bÄƒiete, pe Dan, mamiferul de 30 de ani, care fusese cÃ®t pe ce sÄƒ fie mÃ®ncat pe dinÄƒuntru de enzime, dar scÄƒpase ÅŸi pentru cÄƒ avea prea puÅ£inÄƒ grÄƒsime Ã®n el, prin care lipazele sÄƒ-ÅŸi facÄƒ drum, Ã®l zguduiau acum serios. Porcii rupÃ®nd unul din carnea vie a celuilalt, ca ÅŸi indiferenÅ£a mÄƒcelarilor, normalÄƒ, Ã®n cazul lor, ca mecanism de protecÅ£ie, Ã®l fÄƒceau sÄƒ se Ã®ntrebe dacÄƒ felul Ã®n care o fÄƒcuse pe Viviana sÄƒ sufere nu era exact acelaÅŸi lucru. BÄƒrbatul Ã®n salopetÄƒ tÄƒindu-le zilnic dinÅ£ii animalelor fÄƒrÄƒ anestezie pÄƒrea mult mai puÅ£in sinistru decÃ®t bÄƒrbatul care hotÄƒrÃ®se Ã®ntr-o dupÄƒ-amiazÄƒ, nici el nu ÅŸtia exact cÃ®nd ÅŸi dacÄƒ hotÄƒrÃ®se ceva cu adevÄƒrat sau doar Ã®i venise un gÃ®nd, unul care s-a menÅ£inut deasupra mai multe ore decÃ®t celelalte, sÄƒ jupoaie de viu animalul simbiotic abia ridicat pe picioare, Ã®n doar trei ani ÅŸi cÃ®teva luni. Nu era nimic metaforic aici: suferinÅ£a e suferinÅ£Äƒ peste tot, o ÅŸtia din spital, iar educaÅ£ia din abator Ã®ÅŸi fÄƒcuse efectul. La fel ca bunicul lui, putea sÄƒ provoace deliberat chinul, fiind Ã®n acelaÅŸi timp empatic, suferind alÄƒturi de vietatea chinuitÄƒ. Nici nu ÅŸtia de ce o fÄƒcuse, nu avea nici un motiv solid pe care l-ar fi putut folosi Ã®ntr-un tribunal, Ã®ntr-un act oficial - unul dar ÅŸi, pe scurt, fÄƒrÄƒ subtilitÄƒÅ£i autojustificatoare. Cel mai simplu rÄƒspuns ar fi fost cÄƒ se Ã®ndrÄƒgostise de Joan, dar nu era nici el convins cÄƒ e rÄƒspunsul adevÄƒrat. Poate o fÄƒcuse ca sÄƒ arate cÄƒ e Ã®n stare de asta, sÄƒ se reconstruiascÄƒ. PurtÃ®nd Ã®n el, Ã®n adÃ®nc, mÃ®ndria cÄƒ a devenit un Panzer de voinÅ£Äƒ ÅŸi control. Trecea nepÄƒsÄƒtor prin supermarket pe lÃ®ngÄƒ rafturile cu alcool, nici nu le mai vedea. Pe lÃ®ngÄƒ pachetele de Å£igÄƒri de la intrare, fÄƒrÄƒ de care pe vremuri nici nu -ÅŸi imagina trezirea din somn. Dar oare ar fi putut ajunge acolo fÄƒrÄƒ ea? Åži-ar mai fi pus vreodatÄƒ dinÅ£ii dacÄƒ nu ar fi fost ea ÅŸi telefoanele ei Ã®ndrÄƒgostite, Ã®ntotdeauna Ã®ndrÄƒgostite, fÄƒrÄƒ pauzÄƒ, de dinainte ÅŸi de dupÄƒ fiecare ÅŸedinÅ£Äƒ la stomatolog? Ea Ã®l ajutase sÄƒ-ÅŸi creeze o viaÅ£Äƒ cu totul nouÄƒ, iar el o dÄƒduse afarÄƒ din viaÅ£a cea nouÄƒ.';


echo fixEncoding ($string ) . "\r\n";


?>